<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\School;
use Illuminate\Support\Facades\DB;

class SchoolsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
       
        $schools = [
            // مدارس غزة
            [
                'name' => 'مدرسة النجاح الحديثة',
                'english_name' => 'Al-Najah Modern School',
                'description' => 'مدرسة حديثة تقدم تعليماً متميزاً مع تركيز على التكنولوجيا والابتكار',
                'logo' => 'School1.jpg',
                'cover_image' => 'School1.jpg',
                'address' => 'حي الرمال، شارع الجلاء',
                'region' => 'قطاع غزة',
                'city' => 'غزة',
                'directorate' => 'مديرية غرب غزة',
                'latitude' => 31.5017,
                'longitude' => 34.4668,
                'type' => 'primary',
                'school_type' => 'حكومية',
                'level' => 'ابتدائي-ثانوي',
                'principal_name' => 'د. أحمد محمود',
                'students_count' => 500,
                'teachers_count' => 45,
                'established' => 2010,
                'rating' => 4.8,
                'reviews_count' => 430,
                'phone' => '+970-8-123-4567',
                'email' => 'info@najah-school.ps',
                'website' => 'https://najah-school.ps',
                'certifications' => json_encode(['ISO 9001', 'معتمدة من وزارة التربية']),
                'achievements' => json_encode(['المركز الأول في المسابقة الوطنية 2023', 'جائزة التميز التعليمي']),
                'features' => json_encode(['مكتبة حديثة', 'مختبرات علمية', 'ملعب رياضي', 'قاعة حاسوب']),
                'is_active' => true,
                'is_featured' => true,
            ],
            [
                'name' => 'مدرسة الأمل النموذجية',
                'english_name' => 'Al-Amal Model School',
                'description' => 'مدرسة نموذجية تهتم بالأنشطة اللامنهجية والتطوير الشامل للطالب',
                'logo' => 'School2.jpg',
                'cover_image' => 'School2.jpg',
                'address' => 'حي الشجاعية',
                'region' => 'قطاع غزة',
                'city' => 'غزة',
                'directorate' => 'مديرية شرق غزة',
                'latitude' => 31.5203,
                'longitude' => 34.4776,
                'type' => 'primary',
                'school_type' => 'خاصة',
                'level' => 'ابتدائية',
                'principal_name' => 'أ. فاطمة حسن',
                'students_count' => 380,
                'teachers_count' => 32,
                'established' => 2008,
                'rating' => 4.6,
                'reviews_count' => 285,
                'phone' => '+970-8-234-5678',
                'email' => 'contact@alamal-school.ps',
                'features' => json_encode(['حديقة أطفال', 'مسرح', 'مكتبة', 'نادي رياضي']),
                'is_active' => true,
                'is_featured' => true,
            ],
            [
                'name' => 'مدرسة الفاروق',
                'english_name' => 'Al-Farouq School',
                'description' => 'مدرسة عريقة تجمع بين الأصالة والحداثة في التعليم',
                'logo' => 'school3.png',
                'cover_image' => 'school3.png',
                'address' => 'حي الزيتون',
                'region' => 'قطاع غزة',
                'city' => 'غزة',
                'directorate' => 'مديرية شرق غزة',
                'latitude' => 31.4939,
                'longitude' => 34.4547,
                'type' => 'secondary',
                'school_type' => 'حكومية',
                'level' => 'ثانوية',
                'principal_name' => 'د. محمد عبد الله',
                'students_count' => 720,
                'teachers_count' => 58,
                'established' => 2015,
                'rating' => 4.5,
                'reviews_count' => 512,
                'phone' => '+970-8-345-6789',
                'features' => json_encode(['مختبر فيزياء', 'مختبر كيمياء', 'مكتبة إلكترونية']),
                'is_active' => true,
                'is_featured' => false,
            ],

            // مدارس الضفة الغربية
            [
                'name' => 'مدرسة القدس الثانوية',
                'english_name' => 'Al-Quds Secondary School',
                'description' => 'مدرسة ثانوية متميزة في قلب القدس',
                'logo' => 'School1.jpg',
                'address' => 'البلدة القديمة',
                'region' => 'الضفة الغربية',
                'city' => 'القدس',
                'directorate' => 'مديرية القدس',
                'latitude' => 31.7767,
                'longitude' => 35.2345,
                'type' => 'secondary',
                'school_type' => 'حكومية',
                'level' => 'ثانوية',
                'principal_name' => 'د. خالد أحمد',
                'students_count' => 680,
                'teachers_count' => 52,
                'established' => 1985,
                'rating' => 4.9,
                'reviews_count' => 620,
                'phone' => '+970-2-234-5678',
                'features' => json_encode(['مختبرات علمية متطورة', 'مكتبة رقمية', 'قاعة مؤتمرات']),
                'is_active' => true,
                'is_featured' => true,
            ],
            [
                'name' => 'مدرسة رام الله الثانوية للبنين',
                'english_name' => 'Ramallah Boys Secondary School',
                'description' => 'مدرسة ثانوية مرموقة للبنين في رام الله',
                'logo' => 'School2.jpg',
                'address' => 'وسط رام الله',
                'region' => 'الضفة الغربية',
                'city' => 'رام الله',
                'directorate' => 'مديرية رام الله',
                'latitude' => 31.9000,
                'longitude' => 35.2100,
                'type' => 'secondary',
                'school_type' => 'حكومية',
                'level' => 'ثانوية',
                'principal_name' => 'أ. عمر يوسف',
                'students_count' => 520,
                'teachers_count' => 48,
                'established' => 1960,
                'rating' => 4.7,
                'reviews_count' => 445,
                'phone' => '+970-2-222-3333',
                'features' => json_encode(['مختبرات علمية', 'مكتبة كبيرة', 'قاعة رياضية']),
                'is_active' => true,
                'is_featured' => true,
            ],
            [
                'name' => 'مدرسة نابلس الثانوية',
                'english_name' => 'Nablus Secondary School',
                'description' => 'مدرسة ثانوية رائدة في شمال الضفة الغربية',
                'logo' => 'School1.jpg',
                'address' => 'حي الشرق',
                'region' => 'الضفة الغربية',
                'city' => 'نابلس',
                'directorate' => 'مديرية نابلس',
                'latitude' => 32.2211,
                'longitude' => 35.2544,
                'type' => 'secondary',
                'school_type' => 'حكومية',
                'level' => 'ثانوية',
                'principal_name' => 'د. سامي حسن',
                'students_count' => 750,
                'teachers_count' => 62,
                'established' => 1980,
                'rating' => 4.6,
                'reviews_count' => 580,
                'phone' => '+970-9-456-7890',
                'features' => json_encode(['مختبرات حديثة', 'مكتبة شاملة', 'قاعة رياضية']),
                'is_active' => true,
                'is_featured' => false,
            ],
            [
                'name' => 'مدرسة الخليل الأساسية',
                'english_name' => 'Hebron Basic School',
                'description' => 'مدرسة تركز على الهوية الوطنية والثقافة الفلسطينية',
                'logo' => 'School2.jpg',
                'address' => 'وسط البلد',
                'region' => 'الضفة الغربية',
                'city' => 'الخليل',
                'directorate' => 'مديرية الخليل',
                'latitude' => 31.5292,
                'longitude' => 35.0936,
                'type' => 'primary',
                'school_type' => 'حكومية',
                'level' => 'أساسية',
                'principal_name' => 'أ. ياسر محمود',
                'students_count' => 520,
                'teachers_count' => 42,
                'established' => 1992,
                'rating' => 4.3,
                'reviews_count' => 320,
                'phone' => '+970-2-345-6789',
                'features' => json_encode(['مكتبة تراثية', 'متحف مصغر', 'حديقة نباتات محلية']),
                'is_active' => true,
                'is_featured' => false,
            ],
            [
                'name' => 'مدرسة بيت لحم الأهلية',
                'english_name' => 'Bethlehem Private School',
                'description' => 'مدرسة أهلية متميزة في مدينة بيت لحم التاريخية',
                'logo' => 'School1.jpg',
                'address' => 'شارع النجمة',
                'region' => 'الضفة الغربية',
                'city' => 'بيت لحم',
                'directorate' => 'مديرية بيت لحم',
                'latitude' => 31.7054,
                'longitude' => 35.1948,
                'type' => 'primary',
                'school_type' => 'أهلية',
                'level' => 'مختلطة',
                'principal_name' => 'د. مريم جورج',
                'students_count' => 340,
                'teachers_count' => 35,
                'established' => 1995,
                'rating' => 4.7,
                'reviews_count' => 280,
                'phone' => '+970-2-567-8901',
                'features' => json_encode(['مكتبة تاريخية', 'معرض فني', 'قاعة مؤتمرات']),
                'is_active' => true,
                'is_featured' => true,
            ],
        ];

        foreach ($schools as $school) {
            School::create($school);
        }

        $this->command->info('✅ تم إضافة ' . count($schools) . ' مدرسة بنجاح!');
    }
}
